travis:
  secure:
    BINSTAR_TOKEN: ggjvUJMxez44J93d5FGmfovm1TlHycNeAvypqtzLF9QdqQECY4sojGXGIQ4vVxJHTS3MVqreqICyK2TImN7P0VdvovcbPScEbc+PBNoAMdko/SV+pYOz84EHqqX2Io2B7ZB1S21e/CUIJA0S+j3BCIl6KRZbNwV1tdU15rNsnro66Ha7IM39Gt99WrBViC5FqYcUqObhnZEDQ2OvKoZxqTAYuWxknnJODcqUKNVNNUEx8Ln01UcQ7+mDRAST2GTpnuTlRvS5Lvvp+ZCtlrD5/YFKA7uR6aNMxOvJXGOIqD/4DLIUFVDFmmyplSkg5uI2/474VnPhFPV3jt9HHWNFRbHPFL7LseWmTW0V3LlRgB2vFKeOBgEzZhsFCJrPnWJ4lEf1Mx85DMo94SIT5BaafuV4t5MRja3LK4evuX/gXQbzC5XuefEaIKgexCtlyBgc21yHRLyBRdhTtz2bLn94y7Zujd+domTOqiwY+QxHUe7yuQICeXdM64OaoMm38ee2TkDIdK8Ux2kbrFs1RlArO5sT+gtlw4U1EVSDw2g/eUphraZOj4HDaohwO0DTK7inMBC/jOz+OzXc+zMihWJ4/KAc+hEwm2xgqMrmHIy36ZULtie1sx7wtPGiP3heb6CsQP5Z8EcE4F74H8cd3LTgYdvZjw7RpKEgXQ1PHz6oeC4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
